"""change errors

Revision ID: c3b1686bbd11
Revises: 
Create Date: 2024-10-13 21:23:15.165730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3b1686bbd11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abouts',
    sa.Column('avatar', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('birthday', sa.DateTime(), nullable=False),
    sa.Column('bio', sa.String(length=300), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=False),
    sa.Column('website_url', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('degree', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=170), nullable=False),
    sa.Column('frelance', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('avatar', 'id')
    )
    op.create_table('contacts',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=170), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resumes',
    sa.Column('file', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('style', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('procent', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('socials',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('style', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('socials')
    op.drop_table('skills')
    op.drop_table('services')
    op.drop_table('resumes')
    op.drop_table('projects')
    op.drop_table('contacts')
    op.drop_table('abouts')
    # ### end Alembic commands ###
